### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by efrecon** [mogria/3source-npm#1]
This repository is missing the implementation of `umask-wrapper-sh` and `container-user.sh` to be usable.

**Comment by efrecon** [comment]
My bad, it was just `umask-wrapper.sh` that was not spelled correctly (notice the `.` instead of the original (badly spelled) `-`). You've received a PR.

**Comment by mogria** [comment]
Thank you for mentioning it, I've fixed it. (I didn't see a pull request?)
